### ISSUE TITLE
aspcud-1.9.4 does not build with boost 1.74.0

### ISSUE THREAD

**Issue by fxcoudert** [potassco/aspcud#7]
There are build errors:

```
cd /tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/build/libcudf && /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DBOOST_ALL_NO_LIB -I/tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf -I/tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/build/libcudf/src -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -std=gnu++14 -o CMakeFiles/libcudf.dir/src/dependency.cpp.o -c /tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/src/dependency.cpp
/tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/src/dependency.cpp:476:81: error: use of undeclared identifier '_1'
            boost::sort(candidates, boost::bind(&ConflictGraph::edgeSort, this, _1, _2));
                                                                                ^
/tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/src/dependency.cpp:476:85: error: use of undeclared identifier '_2'
            boost::sort(candidates, boost::bind(&ConflictGraph::edgeSort, this, _1, _2));
                                                                                    ^
In file included from /tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/src/dependency.cpp:26:
In file included from /tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/cudf/dependency.hh:31:
In file included from /usr/local/include/boost/multi_index/random_access_index.hpp:18:
/usr/local/include/boost/bind/bind.hpp:388:16: error: no matching function for call to object of type 'boost::_mfi::mf2<bool,
      ConflictGraph, Package *, Package *>'
        return unwrapper<F>::unwrap(f, 0)(a[base_type::a1_], a[base_type::a2_], a[base_type::a3_]);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/bind/bind.hpp:1318:16: note: in instantiation of function template specialization
      'boost::_bi::list3<boost::_bi::value<ConflictGraph *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> >
      >::operator()<bool, boost::_mfi::mf2<bool, ConflictGraph, Package *, Package *>, boost::_bi::rrlist2<Package *&, Package *&>
      >' requested here
        return l_( type<result_type>(), f_, a, 0 );
               ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:3944:17: note: 
      in instantiation of function template specialization 'boost::_bi::bind_t<bool, boost::_mfi::mf2<bool, ConflictGraph, Package
      *, Package *>, boost::_bi::list3<boost::_bi::value<ConflictGraph *>, boost::arg<1>,
      boost::_bi::value<std::__1::placeholders::__ph<2> > > >::operator()<Package *&, Package *&>' requested here
            if (__comp(*--__last, *__first))
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:4125:12: note: 
      in instantiation of function template specialization 'std::__1::__sort<boost::_bi::bind_t<bool, boost::_mfi::mf2<bool,
      ConflictGraph, Package *, Package *>, boost::_bi::list3<boost::_bi::value<ConflictGraph *>, boost::arg<1>,
      boost::_bi::value<std::__1::placeholders::__ph<2> > > > &, Package **>' requested here
    _VSTD::__sort<_Comp_ref>(__first, __last, _Comp_ref(__comp));
           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:4158:12: note: 
      in instantiation of function template specialization 'std::__1::sort<Package **, boost::_bi::bind_t<bool,
      boost::_mfi::mf2<bool, ConflictGraph, Package *, Package *>, boost::_bi::list3<boost::_bi::value<ConflictGraph *>,
      boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > > &>' requested here
    _VSTD::sort<_Tp*, _Comp_ref>(__first.base(), __last.base(), __comp);
           ^
/usr/local/include/boost/range/algorithm/sort.hpp:51:10: note: in instantiation of function template specialization
      'std::__1::sort<Package *, boost::_bi::bind_t<bool, boost::_mfi::mf2<bool, ConflictGraph, Package *, Package *>,
      boost::_bi::list3<boost::_bi::value<ConflictGraph *>, boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > >
      >' requested here
    std::sort(boost::begin(rng), boost::end(rng), pred);
         ^
/tmp/aspcud-20201117-58896-1qlgy9k/aspcud-1.9.4/libcudf/src/dependency.cpp:476:20: note: in instantiation of function template
      specialization 'boost::range::sort<std::__1::vector<Package *, std::__1::allocator<Package *> >, boost::_bi::bind_t<bool,
      boost::_mfi::mf2<bool, ConflictGraph, Package *, Package *>, boost::_bi::list3<boost::_bi::value<ConflictGraph *>,
      boost::arg<1>, boost::_bi::value<std::__1::placeholders::__ph<2> > > > >' requested here
            boost::sort(candidates, boost::bind(&ConflictGraph::edgeSort, this, _1, _2));
                   ^
/usr/local/include/boost/bind/mem_fn_template.hpp:278:7: note: candidate function not viable: no known conversion from
      'std::__1::placeholders::__ph<2>' to 'Package *' for 3rd argument
    R operator()(T * p, A1 a1, A2 a2) const
      ^
/usr/local/include/boost/bind/mem_fn_template.hpp:283:25: note: candidate function template not viable: no known conversion from
      'std::__1::placeholders::__ph<2>' to 'Package *' for 3rd argument
    template<class U> R operator()(U & u, A1 a1, A2 a2) const
                        ^
/usr/local/include/boost/bind/mem_fn_template.hpp:291:25: note: candidate function template not viable: no known conversion from
      'std::__1::placeholders::__ph<2>' to 'Package *' for 3rd argument
    template<class U> R operator()(U const & u, A1 a1, A2 a2) const
                        ^
/usr/local/include/boost/bind/mem_fn_template.hpp:299:7: note: candidate function not viable: no known conversion from
      'ConflictGraph *' to 'ConflictGraph &' for 1st argument; dereference the argument with *
    R operator()(T & t, A1 a1, A2 a2) const
      ^
```

**Comment by fxcoudert** [comment]
Patch that fixes the issue:

```
diff -pur aspcud-1.9.4-old/libcudf/src/dependency.cpp aspcud-1.9.4/libcudf/src/dependency.cpp
--- aspcud-1.9.4-old/libcudf/src/dependency.cpp	2017-09-19 12:48:41.000000000 +0200
+++ aspcud-1.9.4/libcudf/src/dependency.cpp	2020-11-17 15:39:33.000000000 +0100
@@ -473,7 +473,7 @@ void ConflictGraph::cliques_(bool verbos
         }
         else {
             PackageList candidates = component, next;
-            boost::sort(candidates, boost::bind(&ConflictGraph::edgeSort, this, _1, _2));
+            boost::sort(candidates, boost::bind(&ConflictGraph::edgeSort, this, boost::placeholders::_1, boost::placeholders::_2));
             // TODO: sort by out-going edges
             do {
                 cliques.push_back(PackageList());
```

**Comment by rkaminsk** [comment]
I fixed it in the master. I decided to kick out `boost::bind` altogether and just use a struct based comparison predicate. It really looks like the code should be ported to modern C++ to get rid of the boost dependency. Except for the parser, the code could be written equally well using C++14...
